app:
  jwt:
    private-key-location: file:./keys/rsa_key.pem
    public-key-location: file:./keys/rsa_key.pub
    access-token-expiration-ms: 43200000 # 12 Hours
    pre-auth-token-expiration-ms: 300000 # 5 Minutes
    setup-token-expiration-ms: 600000 # 10 Minutes
  secret:
    admin-password: '${ADMIN_PASSWORD}'
    mfa-secret: '${MFA_SECRET}'

spring:
  application:
    name: 'finance_module'
  mongodb:
    uri: '${MONGO_URL}'
  mvc:
    apiversion:
      required: true
      use:
        path-segment: 1
      supported:
        - 1
  ai:
    openai:
      api-key: '${OPENAI_API_KEY}'
    chat:
      options:
        model: gpt-4o-mini

logging:
  file:
    path: ./logs

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 15
      total-size-cap: 1GB
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.%i.log

  level:
    root: INFO
    com.samuelfilho_dev.finance_module: DEBUG
    org.springframework: WARN
    org.hibernate: DEBUG

  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level) %clr(${PID:- }){magenta} --- [%thread] %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${PID:- } --- [%thread] %-5level %logger{36} - %msg%n"
