app:
  jwt:
    private-key-location: file:./keys/rsa_key.pem
    public-key-location: file:./keys/rsa_key.pub
    access-token-expiration-ms: 43200000 # 12 Hours
    pre-auth-token-expiration-ms: 300000 # 5 Minutes
    setup-token-expiration-ms: 600000 # 10 Minutes
  secret:
    mfa-secret: '${MFA_SECRET}'

spring:
  application:
    name: 'finance_module'
  mongodb:
    uri: '${MONGO_URL}'
  mvc:
    apiversion:
      required: true
      use:
        path-segment: 1
      supported:
        - 1